import Head from 'next/head'

import Link from 'next/link'
import React, { useState } from 'react';

const Nav = (props) => {
    const [isOpen, setIsOpen] = useState(false);
    const { theme, setTheme } = props
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className='main dark:bg-zinc-900' >
                <nav className='bg-white flex items-center justify-between flex-row py-9 text-2xl font-semibold dark:bg-zinc-900 dark:text-white  '>
                    <div className='sm:text-center'>
                        Raouf Bouarrata
                    </div>
                    <div className='flex'>
                        <ul onClick={() => { setIsOpen(!isOpen) }} className={`flex flex-row transition-all ease-in duration-500 ${isOpen ? 'max-lg:flex max-lg:font-bold max-lg:bg-gray-200 dark:max-lg:bg-gray-800  max-lg:bg-opacity-95 dark:max-lg:bg-opacity-95 max-lg:flex-col max-lg:items-center max-lg:absolute max-lg:top-24 max-lg:w-full max-lg:p-5 max-lg:z-10 max-lg:right-0 max-lg:h-full' : 'max-lg:hidden'} `} >
                            <li className='mx-4 max-lg:my-3'><Link href='/'>Home</Link></li>
                            <li className='mx-4 max-lg:my-3'><Link href='/blogs'>Blogs</Link></li>
                            <li className='mx-4 max-lg:my-3'><Link href='/about'>About</Link></li>
                        </ul>
                        <img src={theme === 'light' || undefined ? './lightMode.png' : './darkMode.png'} alt='theme' className='right-0 hover:cursor-pointer' onClick={() => {  theme === 'light' ? setTheme('dark') : setTheme('light');}} />
                        <button className={`hidden max-lg:block max-lg:mx-4 dark:invert `} onClick={() => { setIsOpen(!isOpen) }}>
                            <img src={isOpen ? './close.png' : './menu.png'} alt='menu' className='' height={30} width={30} />
                        </button>
                    </div>
                </nav>
            </div>
        </>
    )
}

export default Nav
